### ISSUE TITLE
How to use it with Apache ?

### ISSUE THREAD

**Issue by IbnSaeed** [neolao/docker-php-5.6.3-fpm-redis#1]
Hello

How can we use it with Apache image
https://registry.hub.docker.com/_/httpd/

and redis server

**Comment by neolao** [comment]
Hello, 

You have to configure Apache with `FastCGIExternalServer`

**Comment by neolao** [comment]
About Redis, you have to connect to the redis server with PHP : https://github.com/phpredis/phpredis
